# Generated by Django 2.0.13 on 2019-03-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_e',
            field=models.CharField(blank=True, max_length=255, verbose_name='英語名'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_e',
            field=models.CharField(blank=True, max_length=100, verbose_name='英語名'),
        ),
        migrations.AddField(
            model_name='food',
            name='page',
            field=models.CharField(blank=True, max_length=100, verbose_name='ページ'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='name_e',
            field=models.CharField(blank=True, max_length=100, verbose_name='英語名'),
        ),
        migrations.AddField(
            model_name='foodstuff',
            name='name_e',
            field=models.CharField(blank=True, max_length=100, verbose_name='英語名'),
        ),
    ]
