# Generated by Django 2.0.13 on 2019-03-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190322_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_e',
            new_name='ename',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name_e',
            new_name='ename',
        ),
        migrations.RenameField(
            model_name='foodcategory',
            old_name='name_e',
            new_name='ename',
        ),
        migrations.RenameField(
            model_name='foodstuff',
            old_name='name_e',
            new_name='ename',
        ),
    ]
